added 4 tests for exit in 05 directory

diff --git a/05_simple_shell_0.3/custom_exit_value b/05_simple_shell_0.3/custom_exit_value
--- a/05_simple_shell_0.3/custom_exit_value
+++ b/05_simple_shell_0.3/custom_exit_value
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-# check that the PATH is checked in the right order
+# check that exit can take arguments as exit codes
 
-command="ls"
+command="exit 98"
 tmp_file="checker_tmp_file_$RANDOM"
 
 # clean up
@@ -11,22 +11,15 @@ rm -f $tmp_file
 
 # create a pseudo random file
 touch $tmp_file
-# empty PATH
-OLDPATH="$PATH"
-PATH=":$PATH"
 # send commands
-$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
-
-# put PATH back
-PATH="$OLDPATH"
-
-# wait a little bit
+$ECHO "$command" | $SHELL 2> /dev/null
+$ECHO "$?" > $OUTPUTFILE 2> /dev/null
+# wait a little
 $SLEEP $SLEEPSECONDS
 
 # check the result
 res=`$CAT "$OUTPUTFILE"`
-
-if [ "$res" == "cisfun" ]; then
+if [ "$res" == "98" ]; then
     print_ok
 else
     print_ko
